version: '3'
services:
  gpt_server:
    # 构建
    build:
      context: .
      dockerfile: Dockerfile.copy
    image: gpt_server:v0.4.0
    shm_size: '4g' # 设置共享内存为4GB
    container_name: gpt_server
    restart: always
    network_mode: host
    # ports:
    #   - "8082:8082"
    volumes:
      - "/home/dev/model/:/home/dev/model/"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # device_ids: [ '0', '1', '2', '3' ]
              count: all
              # count: 2  # 两种方式
              capabilities: [ gpu ]
    command: sh gpt_server/script/start.sh
