[project]
name = "gpt_server"
version = "0.3.2"
description = "gpt_server是一个用于生产级部署LLMs或Embedding的开源框架。"
readme = "README.md"
license = { text = "Apache 2.0" }
authors = [{ name = "Yu Liu", email = "506610466@qq.com" }]
requires-python = ">=3.10"
dependencies = [
    "accelerate>=1.0.1",
    "fastapi==0.114.1",
    "ffmpy @ git+https://gitee.com/liuyu_1997/ffmpy.git",
    "fschat==0.2.36",
    "gradio==4.26.0",
    "infinity-emb[all]==0.0.53",
    "lmdeploy @ git+https://gitee.com/liuyu_1997/lmdeploy.git",
    "loguru>=0.7.2",
    "openai==1.45.0",
    "setuptools==75.2.0",
    "streamlit==1.39.0",
    "torch==2.5.1",
    "torchvision==0.20.1",
    "transformers==4.45.2",
    "vllm==0.6.4.post1",
    "qwen_vl_utils",
]


[project.scripts]
gpt_server = "gpt_server.cli:main"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
