# 后台启动 nohup sh start.sh > gptserver.log &
serve_args:
  host: 0.0.0.0
  port: 8082

models:
  - glm-4v:  #自定义的模型名称
      alias: null # 别名     例如  gpt4,gpt3
      enable: false  # false true
      model_name_or_path: /home/dev/model/THUDM/glm-4v-9b/
      model_type: chatglm  # qwen  chatglm3 yi internlm
      work_mode: lmdeploy-pytorch  # vllm hf lmdeploy-turbomind  lmdeploy-pytorch
      device: gpu  # gpu / cpu
      workers:
      - gpus:
        # - 1
        - 0
  - internvl2:  #自定义的模型名称
      alias: null # 别名     例如  gpt4,gpt3
      enable: true  # false true
      model_name_or_path: /home/dev/model/OpenGVLab/InternVL2-40B-AWQ/
      model_type: internvl2  # qwen  chatglm3 yi internlm
      work_mode: lmdeploy-turbomind  # vllm hf lmdeploy-turbomind  lmdeploy-pytorch
      device: gpu  # gpu / cpu
      workers:
      - gpus:
        # - 1
        - 0
      # - gpus:
      #   - 0
  - chatglm4:  #自定义的模型名称
      alias: chatglm3 # 别名     例如  gpt4,gpt3
      enable: false  # false true
      model_name_or_path: /home/dev/model/ZhipuAI/glm-4-9b-chat
      model_type: chatglm  # qwen  chatglm3 yi internlm
      work_mode: vllm  # vllm hf lmdeploy-turbomind  lmdeploy-pytorch
      device: gpu  # gpu / cpu
      workers:
      - gpus:
        # - 1
        - 0
  
  - qwen:  #自定义的模型名称
      alias: gpt-4,gpt-3.5-turbo,gpt-3.5-turbo-16k # 别名     例如  gpt4,gpt3
      enable: true  # false true
      model_name_or_path: /home/dev/model/qwen/Qwen1___5-14B-Chat/ 
      model_type: qwen  # qwen  chatglm3 yi internlm
      work_mode: vllm  # vllm hf lmdeploy-turbomind  lmdeploy-pytorch
      device: gpu  # gpu / cpu
      workers:
      - gpus:
        - 1
      # - gpus:
      #   - 3
  - qwen-72b:  #自定义的模型名称
      alias: null # 别名     例如  gpt4,gpt3
      enable: true  # false true
      model_name_or_path: /home/dev/model/qwen/Qwen2-72B-Instruct-AWQ/
      model_type: qwen  # qwen  chatglm3 yi internlm
      work_mode: vllm  # vllm hf lmdeploy-turbomind  lmdeploy-pytorch
      device: gpu  # gpu / cpu
      workers:
      - gpus:
        - 3

  - mixtral:  #自定义的模型名称
      alias: null # 别名     例如  gpt4,gpt3
      enable: false  # false true
      model_name_or_path: /home/dev/model/NousResearch/Nous-Hermes-2-Mixtral-8x7B-SFT/
      model_type: qwen  # qwen  chatglm3 yi internlm
      work_mode: vllm  # vllm hf lmdeploy-turbomind  lmdeploy-pytorch
      device: gpu  # gpu / cpu
      workers:
      - gpus:
        - 3
        - 0
    

  - llama3:  #自定义的模型名称
      alias: null # 别名     例如  gpt4,gpt3
      enable: false  # false true
      model_name_or_path: /home/dev/model/unsloth/unsloth/llama-3-8b-Instruct/
      model_type: llama  # qwen  chatglm3 yi internlm
      work_mode: hf  # vllm hf lmdeploy-turbomind  lmdeploy-pytorch
      device: gpu  # gpu / cpu
      workers:
      - gpus:
        - 0

  - yi:  #自定义的模型名称
      alias: null # 别名     例如  gpt4,gpt3
      enable: false  # false true
      model_name_or_path: /home/dev/model/01ai/Yi-34B-Chat/
      model_type: yi  # qwen  chatglm3 yi internlm
      work_mode: hf  # vllm hf lmdeploy-turbomind  lmdeploy-pytorch
      device: gpu  # gpu / cpu
      workers:
      - gpus:
        - 2
        # - 0

  - internlm2:  #自定义的模型名称
      alias: null # 别名     例如  gpt4,gpt3
      enable: false  # false true
      model_name_or_path: /home/dev/model/Shanghai_AI_Laboratory/internlm2_5-7b-chat/
      model_type: internlm  # qwen  chatglm3 yi internlm
      work_mode: hf  # vllm hf lmdeploy-turbomind  lmdeploy-pytorch
      device: gpu  # gpu / cpu
      workers:
      - gpus:
        - 0
    
  # Embedding 模型
  - piccolo-base-zh:
      alias: null # 别名   
      enable: true  # false true
      model_name_or_path: /home/dev/model/assets/embeddings/sensenova/piccolo-base-zh/
      model_type: embedding_infinity # embedding_infinity
      work_mode: hf
      device: gpu  # gpu / cpu
      workers:
      - gpus:
        - 2

  - bce-embedding-base_v1:
      alias: text-embedding-ada-002 # 别名   
      enable: false  # false true
      model_name_or_path: /home/dev/model/maidalun1020/bce-embedding-base_v1/
      model_type: embedding # embedding_infinity
      work_mode: hf
      device: gpu  # gpu / cpu
      workers:
      - gpus:
        - 2

  - bce-reranker-base_v1:
      alias: null # 别名   
      enable: false  # false true
      model_name_or_path: /home/dev/model/maidalun1020/bce-reranker-base_v1/
      model_type: embedding # embedding_infinity
      work_mode: hf
      device: gpu  # gpu / cpu
      workers:
      - gpus:
        - 0
  - bge-reranker-base:
      alias: null # 别名   
      enable: true  # false true
      model_name_or_path: /home/dev/model/Xorbits/bge-reranker-base/
      model_type: embedding_infinity # embedding_infinity
      work_mode: hf
      device: gpu  # gpu / cpu
      workers:
      - gpus:
        - 2
  - bge-base-zh:
      alias: null # 别名   
      enable: false  # false true
      model_name_or_path: /home/dev/model/Xorbits/bge-base-zh-v1___5/
      model_type: embedding # embedding_infinity
      work_mode: hf
      device: gpu  # gpu / cpu
      workers:
      - gpus:
        - 2
  
  - acge_text_embedding:
      alias: text-embedding-ada-002 # 别名   
      enable: true  # false true
      model_name_or_path: /home/dev/model/aspire/acge_text_embedding
      model_type: embedding_infinity # embedding_infinity
      work_mode: hf
      device: gpu  # gpu / cpu
      workers:
      - gpus:
        - 2
  - yinka:
      alias: null # 别名   
      enable: false  # false true
      model_name_or_path: /home/dev/model/Classical/Yinka/
      model_type: embedding # embedding_infinity
      work_mode: hf
      device: gpu  # gpu / cpu
      workers:
      - gpus:
        - 2
  - xiaobu-embedding:
      alias: null # 别名   
      enable: true  # false true
      model_name_or_path: /home/dev/model/lier007/xiaobu-embedding-v2/
      model_type: embedding_infinity # embedding_infinity
      work_mode: hf
      device: gpu  # gpu / cpu
      workers:
      - gpus:
        - 2








