name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3
    # 登录 Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    # 构建 Docker 镜像
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/gpt_server:latest .
    # 推送镜像到 Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/gpt_server:latest
